#!/bin/bash
# <TAGS>programming plotLDAS</TAGS>

# PRINT INSTRUCTIONS IF NO ARGUMENTS ARE GIVEN
if [ $# -lt 1 ]; then
	echo -e "\n--------------------------------------------------------------------------------"
	echo -e $thisprog": convert a hex colour value to an RGB triplet (0-1 range)"
	echo -e "USAGE: $thisprog [hex]"
	echo -e "	[in]: hex colour, eg 11001A"
	echo -e "--------------------------------------------------------------------------------\n"
	exit
fi

# strip quotes and has-symbols from the string if they are present
hex=$(echo $1| tr -d '#' | tr -d '"')

red=$(echo $hex | cut -c 1-2)
green=$(echo $hex | cut -c 3-4)
blue=$(echo $hex | cut -c 5-6)

R=$(echo -e "scale=3 ; $((16"#"$red)) / 255" | bc)
G=$(echo -e "scale=3 ; $((16"#"$green)) / 255" | bc)
B=$(echo -e "scale=3 ; $((16"#"$red)) / 255" | bc)

echo -e $R"\t"$G"\t"$B
