#!/bin/bash
# <TAGS>programming plotLDAS</TAGS>

# PRINT INSTRUCTIONS IF NO ARGUMENTS ARE GIVEN
if [ $# -lt 1 ]; then
	echo -e "\n--------------------------------------------------------------------------------"
	echo -e $thisprog": convert a hex colour value to an RGB triplet (0-1 range)"
	echo -e "USAGE: $thisprog [hex]"
	echo -e "	[in]: hex colour, eg 11001A"
	echo -e "--------------------------------------------------------------------------------\n"
	exit
fi

# strip quotes and has-symbols from the string if they are present
hex=$(echo $1| tr -d '#' | tr -d '"')

# pull out the colour components - first 3 pairs of characters
r1=$(echo $hex | cut -c 1-2)
g1=$(echo $hex | cut -c 3-4)
b1=$(echo $hex | cut -c 5-6)

# convert to 0-255 decimal, then to 0-1 using awk
r1=$(echo $((16"#"$r1)) | awk '{ printf("%.3f",($1/255)) }')
g1=$(echo $((16"#"$g1)) | awk '{ printf("%.3f",($1/255)) }')
b1=$(echo $((16"#"$b1)) | awk '{ printf("%.3f",($1/255)) }')

echo -e $r1"\t"$g1"\t"$b1
