#!/bin/bash
# <TAGS> MED behaviour </TAGS>

thisprog="xs-ldas-medpavprob1"
tempfile="temp_"$thisprog ; rm -f $tempfile*
outbase="pavprob1"

outfileA=$outbase"_data.txt"
outfileB=$outbase"_average.txt"
outfileC=$outbase"_summary.txt"

blocklabels="CS_0-5 CS_5-10 PreCS_0-5 PreCS_5-10 reward ITI"
difflabels="CS-PreCS_0-5 CS-PreCS_5-10 CS-PreCS_0-10"

if [ $# -lt 1 ]; then
	echo
	echo "--------------------------------------------------------------------------------"
	echo $thisprog":  process multiple MED-PC files for probabilistic Pavolovian training"
	echo "- input files must be formatted as per requirements of  xe-ldas-readmed2"
	echo "USAGE: "$thisprog" [database]"
	echo "	[databaseb]: file in format <filename><tab><group_code>"
	echo "EXAMPLE: "
	echo "	"$thisprog" db_experiment1.txt"
	echo "OUTPUT: "
	echo "	"$outfileA" : transformed data from  MED-PC file"
	echo "	"$outfileB" : averages by trial-type"
	echo "	"$outfileC" : summary, one line per subject"
	echo "--------------------------------------------------------------------------------"
	echo
	exit
fi

# READ THE REQUIRED COMMAND-LINE ARGUMMENTS
filedb=$1; shift
if [ ! -e $filedb ] ; then { echo ; echo "--- Error ["$thisprog"]: database file $filedb missing" ; echo ; echo ; exit ; } ; fi

# store column/label identifiers
echo $blocklabels $difflabels | tr ' ' '\n' | xe-timestamp1 stdin -o 2 | awk '{printf("%d\t%s\n",$1,$2)}' > $tempfile".labelkey"

# print headers to output files
echo "subj trial t.type " $blocklabels $difflabels | xe-delimit stdin > $outfileA
echo "subj t.type column label n mean sd sem " | xe-delimit stdin > $outfileB
echo -n "subj grp t.type "$blocklabels $difflabels | xe-delimit stdin > $outfileC


cat $filedb | awk '$0!~/^#/&&NF>1{print$0}' |  while read infile grp ; do

	if [ -e $infile ] ; then echo "	processing $infile "
	else { echo ; echo "--- Error ["$thisprog"]: MED-PC file $infile missing" ; echo ; echo ; exit ; }
	fi


	# GET SUBJECT NAME FROM FILE NAME
	subj=$(echo $infile | cut -f 1 -d _ | awk '{printf("%03d",$1)}' )

	# READ & CONVERT THE MED-PC FILE
	# CALCULATE THE DIFFERENCES STARTING AT LINE2 (EXCLUDE THE HEADER)
	# this will append the differences to the end of the original lines
	echo "subj trial t.type " $blocklabels $difflabels | xe-delimit stdin > $tempfile".data"
	xe-ldas-readmed2 $infile -r 1 |
		tail -n +2 |
		# ignore trial type zero and calculate differencecs
		awk '$2!=0{print "'$subj'",$0,($3-$5),($4-$6),(($3+$4)-($5+$6))}' |
		xe-delimit stdin >> $tempfile".data"
	# compile data to master data output file
	tail -n +2 $tempfile".data" >> $outfileA

	# CALCULATE THE AVERAGE FOR EACH COLUMN (WITHIN-TRIAL BLOCK AND DIFFERENCES) - IGNORE TRIAL NUMBER
	outfile2="average_"$infile
	echo "subj t.type column label n mean sd sem " | xe-delimit stdin > $tempfile".average"
	cut -f 3- $tempfile".data" |
	# transpose the input colmns, keeping the trial type column
	xe-transpose1 stdin -start 2 -n 1 | xe-checkisnum2 stdin -t 2 -f 0 -m "-" |
	# get the average for each trial-type and column (block or difference)
	xe-statsgrp2 stdin | xe-checkisnum2 stdin -t 2 -f 0 -m "-" > $tempfile".0"
	# insert the label key in the output of the averages
	cut -f 1  $tempfile".0" > $tempfile".1"
	cut -f 2  $tempfile".0" | xe-dbmatch2 stdin $tempfile".labelkey" > $tempfile".2"
	cut -f 3- $tempfile".0" > $tempfile".3"
	paste $tempfile".1" $tempfile".2" $tempfile".3" | awk '{print "'$subj'\t"$0}' >> $tempfile".average"
	# compile averages to master average output file
	tail -n +2 $tempfile".average" >> $outfileB

	# TRANSPOSE THE RESULTS FOR EACH TRIAL TYPE
	# get a list of trial types
	list=$(xe-cut1 $tempfile".average" t.type | tail -n +2 | sort -nu)
	for trialtype in $list ; do
		echo -n $subj $grp $trialtype" "
		# only keep the trial type, column number, and mean
		xe-cut1 $tempfile".average" t.type,column,mean -o 1 |
			awk '$1=="'$trialtype'"{printf("%.3f\n",$3)}' |
			xe-transpose2 stdin
	done | xe-delimit stdin >> $outfileC

done

rm -f $tempfile*
