#!/bin/bash
# <TAGS> string </TAGS>

thisprog="xs-match"

if [ $# -lt 2 ]; then
	echo
	echo "---------------------------------------------------------"
	echo $thisprog": determine if a word is a member of a list"
	echo "- USAGE: "$thisprog" [word] [list]"
	echo "	[word]: word to be matched (no spaces)"
	echo "	[list]: list of words to be checked against"
	echo "- EXAMPLE: "$thisprog" 3  1 2 3 4 5 6 "
	echo "---------------------------------------------------------"
	echo
	exit
fi

word=$1 ; shift ; list=$@

for i in $list ; do if [ "$word" == "$i" ] ; then echo $i ; fi ; done
