#!/bin/bash
# <TAGS> programming </TAGS>

thisprog="xs-proggit1"
# define temporary file name, incorporating current process-id
tempfile="temp_"$thisprog #"."$$"."

start_dir=$(pwd)
start_time=$(date +'%s.%3N')
basepath=$(which xs-template 2>/dev/null | rev | cut -f 2- -d / |rev)

setmessage=""
setupdate="0";


if [ $# -lt 1 ]; then
	echo
	echo "--------------------------------------------------------------------------------"
	echo $thisprog": Git helper script"
	echo "REQUIRES: a properly formatted ,notes file"
	echo "USAGE: "
	echo "	"$thisprog" [mode]"
	echo "	[mode]: status, diff, push, or pull"
	echo "		status: show local changes (committed=green, uncommitted=red)"
	echo "		diff: compare local commited changes to remote master"
	echo "		pull: pull remote master repository"
	echo "		push: add changes, commit (with -m message), and push to remote master"
	echo "ADDITIONAL ARGUMENTS (defaults in []):"
	echo "	-m: message for push ["$setmessage"]"
	echo "	-u: update option for pull (0=NO,1=YES) [$setupdate]"
	echo "EXAMPLE: "
	echo "	"$thisprog" data.txt"
	echo "--------------------------------------------------------------------------------"
	echo
	exit
fi


########################################################################################
# REQUIRED ARGUMENT HANDLING
########################################################################################
mode=$1 ; shift

########################################################################################
# OPTIONAL ARGUMENT HANDLING
########################################################################################
vs="m:u:" ; vl="verb:"
y=$(getopt -o $vs -l $vl -n "" -- "$@" 2>&1 > /dev/null)
if [ "$y" != "" ] ; then { echo -e "\n--- Error ["$thisprog"]"$y"\n" ; exit ; }
else eval set -- $(getopt -o $vs -l $vl -n "" -- "$@") ; fi

while [ $# -gt 0 ] ; do
	case $1 in
		-m ) setmessage=$2 ; shift ;;
		-u ) setupdate=$2 ; shift ;;
		-- ) shift ; break ;;
		* ) ;;
	esac
	shift
done

if [ "$setmessage" == "" ] ; then setmessage=$(git status --porcelain) ; fi
if [ "$setupdate" != "0" ] && [ "$setupdate" != "1" ] ; then { echo -e "\n--- Error ["$thisprog"]: invalid --update ($setupdate) -  must be 0 or 1\n" ;  exit; } ; fi

cd $basepath

if [ $mode == "status" ] ; then
	echo "
	git status
	"
	git status
fi
if [ $mode == "diff" ] ; then
	echo "
	git fetch origin master
	git diff --summary FETCH_HEAD
	"
	git fetch origin master
	git diff --summary FETCH_HEAD
fi
if [ $mode == "push" ] ; then
	echo "
	git add --all .
	git commit -a -m \"$setmessage\"
	git push -u origin master
	"
	git add --all # also records removals
	git commit -a -m "$setmessage"
	git push -u origin master
fi
if [ $mode == "pull" ] ; then
	if [ $setupdate == "1" ] ; then
		git remote update > $tempfile
		list=$(git diff origin/master --name-only | grep -- 'xe-' | grep '.c' --color=never | cut -f 2 -d /)
	fi

	echo -e "\ngit pull origin master"
	git pull origin master

	if [ "$setupdate" == "1" ] && [ "$list" != "" ] ; then
		xs-progcompile "$list" --warn 1
	fi
fi

cd $start_dir
exit
