#!/bin/bash
# <TAGS> R </TAGS>

################################################################################
# INTIAL VARIABLE DEFINITIONS
################################################################################
thisprog=`basename "$0"`
tempfile="temp_"$thisprog #"."$$"."
datafile=$tempfile".txt"
scriptfile=$tempfile".R"
setplot="1"
setclean="1"
plotfile="plot_"$thisprog".pdf"

################################################################################
# PRINT INSTRUCTIONS IF NO ARGUMENTS ARE GIVEN
################################################################################
if [ $# -lt 3 ]; then
	echo
	echo "--------------------------------------------------------------------------------"
	echo "- Perform ANOVA using R"
	echo "- Will perform Tukey's HSD post-hoc tests"
	echo "- Non-numeric values for the dependent varaiable will be treated as NAN"
	echo "- Predictors can be numeric or alpha-numeric"
	echo ""
	echo "USAGE: "
	echo "	$thisprog [file] [y] [list] [opt]"
	echo ""
	echo "	[file]:  input file with headered columns"
	echo "	[y]: name of the column containing the dependent variable"
	echo "	[list]: CSV list of column-names for predictors"
	echo "	[opt]: options (see below)"
	echo ""
	echo "VALID OPTIONS (defaults in []):"
	echo "	--plot: create a .pdf plot for the ANOVA (0=NO 1=YES) [$setplot]"
	echo "		- output sent to $plotfile"
	echo "		- NOTE: currently only implemented for 1- or 2-way ANOVAs"
	echo "	--clean: remove temporary files (0=NO 1=YES) [$setclean]"
	echo ""
	echo "EXAMPLE: "
	echo "	"$thisprog" data.txt  height  age,sex,income"
	echo "--------------------------------------------------------------------------------"
	echo
	exit
fi

########################################################################################
# REQUIRED ARGUMENT HANDLING
########################################################################################
infile=$1; shift
data=$1; shift
predictors=$1; shift
########################################################################################
# OPTIONAL ARGUMENT HANDLING
########################################################################################
vs="c:" ; vl="clean:,plot:"
y=$(getopt -o $vs -l $vl -n "" -- "$@" 2>&1 > /dev/null)
if [ "$y" != "" ] ; then { echo -e "\n--- Error ["$thisprog"]"$y"\n" ; exit ; }
else eval set -- $(getopt -o $vs -l $vl -n "" -- "$@") ; fi
while [ $# -gt 0 ] ; do
	case $1 in
		--clean ) setclean=$2 ; shift ;;
		--plot )  setplot=$2 ; shift ;;
		-- ) shift ; break ;;
		* ) ;;
	esac
	shift
done
if [ "$setclean" != "0" ] && [ "$setclean" != "1" ] ; then { echo -e "\n--- Error ["$thisprog"]: invalid --clean ($setclean) -  must be 0 or 1\n" ;  exit; } ; fi
if [ "$setplot" != "0" ] && [ "$setplot" != "1" ] ; then { echo -e "\n--- Error ["$thisprog"]: invalid --plot ($setplot) -  must be 0 or 1\n" ;  exit; } ; fi
if [ "$setclean" == "1" ] ; then
	if [ "$tempfile" != "" ] ; then rm -f $tempfile* ; fi
fi

########################################################################################
# CREATE A DATAFILE WITH INVALID OR NON-FINITE NUMBERS RENAMED
########################################################################################
xe-cut1 $infile $data,$predictors -s 1 > $tempfile
head -n 1 $tempfile > $datafile
xe-checkisnum2 $tempfile -f 1 -t 2 -c 1 -m "-" |
	xe-strsub1 stdin "-" "NA" |
	xe-strsub1 stdin "NAN" "NA" |
	xe-strsub1 stdin "NaN" "NA" |
	xe-strsub1 stdin "Nan" "NA" |
	xe-strsub1 stdin "nan" "NA" >> $datafile

#cat $infile > $datafile


########################################################################################
# CREATE AN R-SCRIPT FILE
########################################################################################
let npred=$(echo $predictors | tr ',' ' ' | wc -w)
listpred1=$(echo $predictors | tr ',' ' ')
listpred2=$(echo $predictors | xe-strsub1 stdin "," " * ")
predfirst=$(echo $predictors | awk -F , '{print $1}')
predlast=$(echo $predictors  | awk -F , '{print $NF}')

# READ THE DATA
echo -e "df <- read.table('"$datafile"', header = TRUE)" > $scriptfile

# SPECIFY THAT PREDICTORS ARE CATEGORICAL FACTORS
for pred in $listpred1 ; do
	echo -e "df\$$pred = as.factor(df\$$pred)" >> $scriptfile
done

# ATTACH THE DATAFRAME
echo "attach(df)" >> $scriptfile

# RUN THE ANOVA
echo "
model <- lm( $data ~ $listpred2)
anova(model)
" >> $scriptfile

# DO THE POST-HOC TESTS - requires an AOV output
echo "TukeyHSD(aov( $data ~ $listpred2))" >> $scriptfile

# PLOT IF REQUIRED
if [ "$setplot==1" ] ; then
	echo -e "" >> $scriptfile
	if [ $npred -lt 3 ] ; then
		echo -e "pdf(\"$plotfile\")" >> $scriptfile
		echo -e "boxplot($data ~ $predlast + $predfirst, notch=F, col=rainbow(length(unique($predlast))))" >> $scriptfile
		echo -e "plot(model)" >> $scriptfile
		echo -e "dev.off()" >> $scriptfile
	fi
fi


########################################################################################
# RUN THE ANALYSIS - SAVE TO FILE
########################################################################################
cat $scriptfile | R -q --no-save --slave > $tempfile

########################################################################################
# SUMMARISE THE OUTPUT
########################################################################################
cat $tempfile |
	xe-cut2 stdin Df -s3 "---" |
	xe-strsub1 stdin " Sq" "_Sq" |
	xe-strsub1 stdin "F value" "F_Value" |
	xe-strsub1 stdin "Pr(>F)" "p" |
	xe-strsub1 stdin "< " "<" |
	awk 'BEGIN{n=0}{if(++n==1) print "Factor\t"$0"\tsig" ; else print $0}' |
	xe-delimit stdin > $tempfile".out.anova"

cat $tempfile | xe-cut2 stdin "---" -s1 1 > $tempfile".out.notes1"
cat $tempfile | xe-cut2 stdin "$" -s3 "null" > $tempfile".out.effects"

dfres=$(cat $tempfile".out.anova" | awk '$1=="Residuals"{print $2}')

echo -e "\n--- ANOVA TABLE FOR $data ------------------------------------------------------"
cat $tempfile".out.anova"
cat  $tempfile".out.notes1"

echo -e "\n--- SUMMARY --------------------------------------------------------------------"
xe-cut1 $tempfile".out.anova" Factor,Df,F_Value,p,sig -o 1 |
	grep -v Residuals |
	awk '{print $1"\tF("$2",'$dfres')= "$3"\tp= "$4"\t"$5}'

echo -e "\n--- MAIN EFFECTS ---------------------------------------------------------------"
cat $tempfile | xe-cut2 stdin "$" -s3 "null"

################################################################################
# CLEANUP AND EXIT
################################################################################
if [ "$setclean" == "1" ] ; then
	if [ "$tempfile" != "" ] ; then rm -f $tempfile* ; fi
fi
exit
